# Generated by Django 4.1.4 on 2023-03-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.TextField()),
                ('dateTime', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('AccessCheck', models.BooleanField()),
                ('AboutStudent', models.TextField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group', to='article.group')),
            ],
        ),
        migrations.CreateModel(
            name='AccessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.TextField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='article.student')),
            ],
        ),
    ]
