# Generated by Django 4.1.4 on 2023-03-31 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_accessqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessqr',
            name='id',
        ),
        migrations.AlterField(
            model_name='accessqr',
            name='data',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='accessqr',
            name='qrData',
            field=models.UUIDField(default=uuid.UUID('6177da1f-c3a2-44e9-b042-3b4564283068'), editable=False, primary_key=True, serialize=False),
        ),
    ]
