# Generated by Django 4.1.4 on 2023-04-01 07:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_accessqr_id_alter_accessqr_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspending',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='accesspending',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessqr',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='accessqr',
            name='qrData',
            field=models.UUIDField(default=uuid.UUID('f57049fe-8299-41ee-b60b-ea78324ea87c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
