# Generated by Django 4.1.4 on 2023-04-01 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_accessqr_qrdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessqr',
            name='qrData',
            field=models.UUIDField(default=uuid.UUID('0384d383-a7e9-4676-901d-9ccd44096c4e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
