# Generated by Django 4.1.4 on 2023-04-01 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_accessqr_qrdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspending',
            name='DeviceName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='accessqr',
            name='qrData',
            field=models.UUIDField(default=uuid.UUID('b88310d9-2dea-4641-8665-ae19d0f7efce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
